language: java
dist: xenial
sudo: false

jdk:
  - openjdk8
  - openjdk11

before_cache:
  - rm -rf $HOME/.m2/repository/io/github/mweirauch/micrometer-jvm-extras

cache:
  directories:
  - $HOME/.m2

install: /bin/true

script: mvn clean install
